Update cipher.rb
https://github.com/elastic/logstash/blob/main/logstash-core/src/main/java/co/elastic/logstash/api/Password.java does not expose `getLength`, we need to use `.value`

**Context**: User got the error below while running Logstash with `cipher` filter plugin used in the pipeline.

```
[ERROR][logstash.javapipeline ][main] Pipeline error {:pipeline_id=>"REDACTED", :exception=>#<NoMethodError: undefined method `length' for <password>:Java::CoElasticLogstashApi::Password>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-cipher-4.0.2/lib/logstash/filters/cipher.rb:125:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:232:in `block in register_plugins'", "org/jruby/RubyArray.java:1821:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:231:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:594:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:244:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:189:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:141:in `block in start'"], "pipeline.sources"=>["REDACTED"], :thread=>"#<Thread:REDACTED run>"}
```